apiVersion: v1
kind: Pod
metadata:
   name: Fluentd-Elasticsearch
   namespace: kube-system
Labels:
   k8s-app: Fluentd-logging
Spec:
   containers:
   - name: Fluentd-Elasticsearch
   image: &lt; Your fd-image &gt;
Resources:
limits:
   memory: 200Mi
Requests:
   cpu: 100m
   memory: 200Mi
   volumeMounts:
   - name: varlog
   mountPath: /var/log
   - name: varlibdockercontainers
   mountPath: /var/lib/docker/containers
   readOnly: true
   terminationGracePeriodSeconds: 30
   volumes:
   - name: varlog
   hostPath:
   path: /var/log
   - name: varlibdockercontainers
   hostPath:
   path: /var/lib/docker/containers
